### ISSUE TITLE
No authentication support

### ISSUE THREAD

**Issue by fwolfst** [treenewbee/activestorage-sftp#1]
As far as I see, there is no authentification support built in. Is that on purpose? What about adding a password-parameter to the configuration and use it when doing the connection?

**Comment by treenewbee** [comment]
Ok, I was thinking use public/private key provides better security, I can add password auth if there is demand for it

**Comment by fwolfst** [comment]
Key-based authentication surely provides better security but might be tricky or impossible to set up on shared hosting environments. I have a working implementation that I can craft a PR of if you want.
