### ISSUE TITLE
urls to image blobs and variants

### ISSUE THREAD

**Issue by fwolfst** [treenewbee/activestorage-sftp#2]
While image upload works, `image_tag` does not resolve to the correct url in my case.

I do not understand the ActiveStorage architecture, but with a bit of spying (https://github.com/iscreen/active-storage-ftp/blob/master/lib/active_storage/service/ftp_service.rb and https://github.com/gordienko/activestorage-ftp/blob/master/lib/active_storage/service/ftp_service.rb) I managed to "fix" image display by modifying `def url`.

However, paths to variants will not work. Are you in maintaining mode and do we dig a bit deeper?

**Comment by fwolfst** [comment]
wrt the variants-thing: there is a PR waiting.

However, afterwards I just looked into how the Disk Storage implemenation of active_storage deals with the issue (https://github.com/rails/rails/blob/master/activestorage/lib/active_storage/service/disk_service.rb) . Probably it would be wise to implement it similar (I believe the easy fix includes implementing a `mkdir_p`-like method for sftp).

**Comment by fwolfst** [comment]
This issue is not yet closed for me, as the generated URL (in url) still points to the local file. I assume you use the sftp as backup-mirror and thus its fine and probably even preferred to have the urls point to the local rails installations assets path.
However, if sftp is the only storage, this will not work. I have patched this locally (basically using the code as in the referenced active*storage-ftp implementations above), but this might break the "sftp as backup only" solution.

My "solution" (again I do not fully understand the architecture) would look like this:

```
      def url(key, expires_in:, filename:, disposition:, content_type:)
          instrument :url, key: key do |payload|
            raise "public_host not defined." unless public_host
            generated_url = [public_host, relative_folder_for(key), key].join('/')

           payload[:url] = generated_url  
           generated_url
        end
     end
```

But probably setting the headers and all that is a good idea, its painting with eyes closed for me.

**Comment by n-studio** [comment]
I have the same issue as @fwolfst and his fix using `relative_folder_for` instead of `folder_for` worked for me.
